referencement:
    pattern:  /
    defaults: { _controller: EcommerceBundle:Referencement:referencement }

referencement_commande:
    pattern:  /commande
    defaults: { _controller: EcommerceBundle:Referencement:refcom }

referencement_commande_getting:
    pattern:  /getting
    defaults: { _controller: EcommerceBundle:Referencement:getting }

referencement_commande_contenu:
    pattern:  /contenu
    defaults: { _controller: EcommerceBundle:Referencement:contenu }

referencement_commande_affichage:
    pattern:  /affichage
    defaults: { _controller: EcommerceBundle:Referencement:affichage }
