referencement:
    pattern:  /
    defaults: { _controller: EcommerceBundle:Referencement:referencement }

referencement_commande:
    pattern:  /commande
    defaults: { _controller: EcommerceBundle:Referencement:refcom }


