budget_gestion_contenu:
    pattern:  /budget_g_c
    defaults: { _controller: EcommerceBundle:Produits:budgetgestiondecontenu }

devis_gestion_contenu:
    pattern:  /devis_g_c
    defaults: { _controller: EcommerceBundle:Produits:devisgestiondecontenu }

budget_affichage:
    pattern:  /budget_affichage
    defaults: { _controller: EcommerceBundle:Produits:budgetaffichage }

devis_affichage:
    pattern:  /devis_affichage
    defaults: { _controller: EcommerceBundle:Produits:devisaffichage }


presentation:
    pattern:  /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:presentation }

categorieProduits:
    pattern:  /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:produits }

rechercheProduits:
    pattern:  /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }


